### ISSUE TITLE
final todo list for 1.0.0 release

### ISSUE THREAD

**Issue by snd** [snd/hinoki#7]
- [x] make all the old tests pass again
- [x] test that lifetime can be ommitted
- [x] test isThenable
- [x] test getNamesToInject
- [x] test factory objects
  - [x] and nested
- [x] test factory arrays
  - [x] and nested
- [x] test the new lifetimes more thoroughly
- [x] test that errored pending promises are removed
- [x] find a new and better solution for debugging and implement it
- [x] solve what happens if a factory returns a promise which returns a promise ?
- [ ] write new readme
  - "a source is a function that takes a name and returns a factory or null"
- [ ] fix examples
- [x] improve/speed-up detection of circular dependencies
- [x] rename `UnresolvableError` to `NotFoundError` because we are no longer resolving
- [ ] salvage the rewrite folder
- [ ] get some distance
- [ ] look over everything again and polish
  - [ ] use lodash wherever possible
- [ ] release

**Comment by snd** [comment]
moved to https://github.com/snd/hinoki/pull/8
